name: IAC workflow

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   
      contents: read   
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws_account_id }}:role/${{ secrets.GH_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init -upgrade -reconfigure 
        working-directory: "."

      - name: Terraform plan
        run: |
          terraform plan -var-file="terraform.tfvars"
        working-directory: "."

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve  -var-file="terraform.tfvars"
        working-directory: "."
